# Generated by Django 5.2.13 on 2026-06-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6, unique=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('options_json', models.JSONField()),
                ('current_index', models.IntegerField()),
                ('takeit_penalty', models.IntegerField()),
                ('declared_suit', models.CharField()),
                ('waiting_game_response', models.CharField(blank=True, max_length=50, null=True)),
                ('game_candidate_id', models.IntegerField()),
                ('bank_json', models.JSONField()),
                ('pot_json', models.JSONField()),
                ('ranking_json', models.JSONField()),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
