# Generated by Django 5.2.13 on 2026-06-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_room_is_private_room_max_players_room_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='room1', max_length=50),
        ),
    ]
