# Generated by Django 5.2.13 on 2026-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game_candidate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
