# Generated by Django 5.2.13 on 2026-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_roomplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_vs_ai',
            field=models.BooleanField(default=False),
        ),
    ]
