# Generated by Django 5.2.13 on 2026-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_tournament_tournamentmatch_tournamentslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_tournament_match',
            field=models.BooleanField(default=False),
        ),
    ]
